# Generated by Django 4.0.1 on 2022-02-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shippingaddress_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
