# Generated by Django 4.0.1 on 2022-02-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
