# Generated by Django 4.0.1 on 2022-02-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
