# Generated by Django 4.0.1 on 2022-02-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_star_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
