# Generated by Django 4.0.1 on 2022-02-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
