# Generated by Django 4.0.1 on 2022-02-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_review_star_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='star_rating',
        ),
    ]
