# Generated by Django 4.0.1 on 2022-02-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_review_star_rating_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
