# Generated by Django 4.0.1 on 2022-02-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
